06_PJT/accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns = [
    # 회원가입
    path('signup/', views.signup, name="signup"),
    # 로그인
    path('login/', views.login, name="login"),
    # 로그아웃
    path('logout/', views.logout, name="logout"),
    # 프로필
    path('<int:user_pk>/', views.profile, name='profile'),
    # 팔로우
    path('<int:user_pk>/follow/', views.follow, name="follow"),
]

06_PJT/boards/urls.py
from django.urls import path
from . import views

app_name="boards"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('<int:board_pk>/', views.detail, name='detail'), 
    path('<int:board_pk>/update/', views.update, name='update'),   
    path('<int:board_pk>/comment/', views.comment, name='comment'),
    path('<int:board_pk>/comment/<int:comment_pk>/', views.comment_detail, name='comment_detail'),
]

06_PJT/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('accounts/', include('accounts.urls')),
]

06_PJT/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    

06_PJT/boards/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Board(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='board')
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='comment')
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

06_PJT/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm

# model 선택 세가지 방법
# 1.  직접 가져오기
# from .models import User
# 2. settings 에 설정된 모델 가져오기
# from django.conf import settings # model = settings.AUTH_USER_MODEL
# > 문자열 > models.py 에 작성할 떄는 문자열로 적는게 좋다
# 3. get_user_model 메서들 활용
from django.contrib.auth import get_user_model


class CustomUsercreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields

06_PJT/boards/forms.py
from django import forms
from .models import Board, Comment

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ('title', 'content', )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

06_PJT/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_POST
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from .models import User
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUsercreationForm


@require_http_methods(['GET', 'POST'])
def signup(request):
    # 로그인한 사용자가 들어오면 ??
    if request.user.is_authenticated:
        return redirect('boards:index')
    
    # Method기 GET 일때와 POST 일 때
    # POST : 실제로 회원 가입 진행
    if request.method == 'POST':
        form = CustomUsercreationForm(request.POST)
        if form.is_valid():
            # 저장 및 자동 로그인
            user = form.save()
            auth_login(request, user)
            return redirect('boards:index')
    else:
        # GET : 회원가입 페이지 보여줘야함
        form = CustomUsercreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)
    

@require_http_methods(['GET', 'POST'])
def login(request):
    # 로그인한 사용자가 들어오면 ??
    if request.user.is_authenticated:
        return redirect('boards:index')
    
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('boards:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

# 세션 데이터를 삭제 > POST 요청
@require_POST
def logout(request):
    # 로그인 안된 사용자가 요청을 보내면 ?
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('boards:index')    

@require_http_methods(['GET'])
def profile(request, user_pk):
    user = get_object_or_404(User, pk=user_pk)
    boards = user.board.all()
    comments = user.comment.all()
    followers = user.followers.all()
    context = {
        'boards': boards,
        'comments': comments,
        'user': user,
        'followers': followers
    }
    return render(request, 'accounts/profile.html', context)


@require_http_methods(["POST"])
def follow(request, user_pk):
    person = get_user_model().objects.get(pk=user_pk)
    # 자기 자신은 팔로우 할 수 없음
    if person != request.user:
        # 이미 팔로우 한 유저라면 삭제
        if person.followers.filter(pk=request.user.pk).exists():
            person.followers.remove(request.user)
        # 새로 팔로우하는 유저라면 추가
        else:
            person.followers.add(request.user)
    return redirect('accounts:profile', person.pk)

06_PJT/boards/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from .models import Board, Comment
from .forms import BoardForm, CommentForm
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required

# Create your views here.
@require_http_methods(["GET"])
def index(request):
    boards = Board.objects.all().order_by('-created_at')
    context = {
        'boards': boards
    }
    return render(request, 'boards/index.html', context)

@require_http_methods(["GET", "POST"])
def detail(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk) 
    if request.method == 'POST':
        board.delete()
        return redirect('boards:index')

    comments = board.comments.all()
    comment_form = CommentForm()
    
    context = {
        'board': board,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'boards/detail.html', context)

@require_http_methods(["GET", "POST"])
def update(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)

    if request.method == 'POST':
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            form.save()
            return redirect('boards:detail', board.pk)
    else:
        form = BoardForm(instance=board)
    context = {
        'board': board,
        'form': form,
    }        
    return render(request, 'boards/update.html', context)

@require_http_methods(["GET", "POST"])
def create(request):
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit = False)
            board.author = request.user
            form.save()
            return redirect('boards:index')
    else:
        form = BoardForm()
    context = {
        'form': form,
    }
    return render(request, 'boards/create.html', context)

@require_http_methods(["POST"])
def comment(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.board = board
            comment.author = request.user
            comment.save()
            return redirect('boards:detail', board.pk)

@require_http_methods(["POST"])
def comment_detail(request, board_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.method == 'POST':
        comment.delete()
        return redirect('boards:detail', board_pk)

06_PJT/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div>
  <h1 class="mb-4">로그인</h1>
  <form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-light">로그인</button>
  </form>
</div>
{% endblock content %}

06_PJT/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-between">
  <div>
    <h1 class="mb-5">{{ user.username }}님의 프로필 페이지</h1>
  </div>
  <div>
    <div class="d-flex">
      <div class="mt-1">
        팔로잉: {{ user.followings.all|length }} / 팔로워: {{ user.followers.all|length }}
      </div>
      <div class="ms-3">
        {% if request.user.is_authenticated and request.user != user %}
          <form action="{% url 'accounts:follow' user.id %}" method='POST'>
            {% csrf_token %}
            {% if request.user in user.followers.all %}
              <button type="submit" class="btn btn-light">Unfollow</button>
            {% else %}
              <button type="submit" class="btn btn-light">follow</button>
            {% endif %}
          </form>
        {% endif%}
      </div>
    </div>
  </div>
</div>

<p>회원번호: {{ user.id }}</p>
<p>유저이름: {{ user.username }}</p>
<p>가입날짜: {{ user.date_joined }}</p>

<hr>

<h2 class="my-4">유저가 쓴 글</h2>

{% if boards|length == 0 %}
  <p>아직 작성한 게시글이 없습니다</p>
{% else %}
  {% for board in boards %}
    <div class="rounded" style="background-color: #f3f3f3;">
      <div class="ms-3 mb-3">
        <p class="pt-2">글번호: {{ board.id }}</p>
        <p class="pb-2">글제목: <a href="{% url 'boards:detail' board.id %}">{{ board.title }}</p></a>
      </div>
    </div>
  {% endfor %}
{% endif %}

<hr>

<h2 class="my-4">유저가 쓴 댓글</h2>

{% if comments|length == 0 %}
  <p>아직 작성한 댓글 없습니다</p>
{% else %}
  {% for comment in comments %}
    <div class="rounded" style="background-color: #f3f3f3;">
      <div class="ms-3 mb-3">
        <p class="pt-2">글제목: <a href="{% url 'boards:detail' comment.board.id %}">{{ comment.board.title }}</p></a>
        <p class="pb-2">내용: {{ comment.content }}</p>
      </div>
    </div>
  {% endfor %}
{% endif %}

<hr>

<h2 class="my-4">팔로워</h2>

{% if followers|length == 0 %} 팔로워 한 사람이 없습니다.
{% else %}
  {% for follower in followers %}
    <div class="my-2 rounded" style="background-color: #f3f3f3;">
      <div class="py-1 d-flex justify-content-between">
        <div>
          <div class="ms-3 mb-3">
            <p class="pt-2">유저: {{ follower.username }}</p>
          </div>
        </div>
        <div>
          <a href="{% url 'accounts:profile' follower.id %}"><button class="mt-1 me-2 btn btn-light">프로필 보러가기</button></a>
        </div>
      </div>
    </div>
  {% endfor %}
{% endif %}

{% endblock content %}

06_PJT/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<div>
  <h1 class="mb-4">회원가입</h1>
  <form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-light">회원가입</button>
  </form>
</div>
{% endblock content %}

06_PJT/boards/templates/boards/create.html
{% extends 'base.html' %}

{% block content %}
<div>
  <h1 class="mb-4">생성 페이지</h1>
  <form action="{% url 'boards:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-light">생성하기</button>
  </form>
</div>
{% endblock content %}

06_PJT/boards/templates/boards/detail.html
{% extends 'base.html' %}

{% block content %}
<div>
  <div class="d-flex justify-content-between">
    <h1 class="mb-4">상세 페이지</h1>
  </div>
  <p>글번호 : {{ board.id }}</p>
  <p>작성자 : {{ board.author }}</p>  
  <p>글제목 : {{ board.title }}</p>
  <p>글내용 : {{ board.content }}</p>
  <p>작성날짜 : {{ board.created_at }}</p>
  <p>수정날짜 : {{ board.updated_at }}</p>
  <hr>
  <div class="mb-5 d-flex justify-content-between">
    <a href="{% url 'boards:index' %}"><button class="btn btn-light">메인 페이지로</button></a>
    <div class="d-flex">
      {% if request.user == board.author %}
      <a href="{% url 'boards:update' board.id %}"><button class="me-3 btn btn-success">수정하기</button></a>
      <form action="{% url 'boards:detail' board.id%}" method='POST'>
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">삭제하기</button>
      </form>
      {% endif %}
    </div>
  </div>
  {% if request.user.is_authenticated %}
    <div>
      <form action="{% url 'boards:comment' board.id %}" method='POST'>
        {% csrf_token %}
        <button class="btn btn-secondary" style="float: right;" type="submit">작성하기</button>
        {{ comment_form.as_p }}
      </form>
    </div>
  {% else %}
    <p class="ms-3">댓글을 작성하시려면 로그인을 해주세요.</p>
  {% endif %}

  <div class="mt-5">
    {% if comments|length == 0 %} 댓글이 없습니다.
    {% else %}
      {% for comment in comments %}
      <div class="my-3 d-flex justify-content-between">
        <div>
          <span>{{ comment.content }}</span>
          <span class="mx-5">({{ comment.created_at }})</span>
        </div>
          <div>
            {% if request.user == comment.author %}
            <form action="{% url 'boards:comment_detail' board.id comment.id %}" method='POST'>
              {% csrf_token %}
              <button class="btn btn-light">삭제하기</button>
            </form>
            {% endif %}
          </div>
        </div>
        <hr/>
      {% endfor %}
    {% endif %}
  </div>
</div>
{% endblock content %}

06_PJT/boards/templates/boards/index.html
{% extends 'base.html' %}

{% block content %}
<div>
  <div class="d-flex justify-content-between">
    <h1 class="mb-4">메인 페이지</h1>
    {% if request.user.is_authenticated %}
      <a style="height: 70%;" href="{% url 'boards:create' %}"><button class="btn btn-info">생성하기</button></a>
    {% endif %}
  </div>
  {% if boards|length == 0 %}아직 게시글이 없습니다
  {% else %}
  {% for board in boards %}
    <p>글번호 : {{ board.id }}</p>
    <p>작성자 : <a href="{% url 'accounts:profile' board.author.id %}" style="text-decoration: none;">{{ board.author }}</a></p>    
    <p>글제목 : <a href="{% url 'boards:detail' board.id %}" style="text-decoration: none;">{{ board.title }}</a></p>
    <hr>
  {% endfor %}
  {% endif %}
</div>
{% endblock content %}

06_PJT/boards/templates/boards/update.html
{% extends 'base.html' %}

{% block content %}
<div>
  <h1 class="mb-4">수정 페이지</h1>
  <form action="{% url 'boards:update' board.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="수정하기">
  </form>
</div>
{% endblock content %}

06_PJT/templates/_navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'boards:index' %}">메인 페이지</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'accounts:profile' request.user.id %}">프로필 페이지</a>
        </li>
        {% endif %}
        {% if request.user.is_authenticated %}
        <form action="{% url "accounts:logout" %}" method='POST'>
          {% csrf_token %}
          <input type="submit" value = "로그아웃">
        </form>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'accounts:signup' %}">회원가입</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'accounts:login' %}">로그인</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

06_PJT/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  <div class="mt-3 container">
    {% if user %}
    <h4>Hello, {{ user }}</h4>
    {% else %}
    <h4>로그인을 해주세요</h4> 
    {% endif %}
    <hr>
    
    <div class="mt-3 mb-4">
      {% include '_navbar.html' %}
    </div>

    <div class="mb-5">
      {% block content %}
      {% endblock content %}
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>