05_PJT/mypjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trends/', include('trends.urls')),
]

05_PJT/mypjt/trends/urls.py
from django.urls import path
from . import views

app_name="trends"
urlpatterns = [
    path('keyword/', views.keyword, name="keyword"),
    path('keyword/<int:pk>/', views.keyword_detail, name="keyword_detail"),
    path('crawling/', views.crawling, name="crawling"),
    path('crawling/histogram/', views.crawling_histogram, name="crawling_histogram"),
    path('crawling/advanced/', views.crawling_advanced, name="crawling_advanced"),
]

05_PJT/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('trends/', include('trends.urls')),
]

05_PJT/mypjt/trends/models.py
from django.db import models

# Create your models here.
class Keyword(models.Model):
    name = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Trend(models.Model):
    name = models.TextField()
    result = models.IntegerField()
    search_period = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

05_PJT/mypjt/trends/views.py
from django.shortcuts import render, redirect
from .models import Keyword, Trend
from bs4 import BeautifulSoup
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager

# Create your views here.
def keyword(request):
    if request.method == 'POST':
        keyword = request.POST.get('keyword')
        Keyword.objects.create(name=keyword)
        return redirect('trends:keyword')

    keywords = Keyword.objects.all()
    context = {
        'keywords': keywords,
    }
    return render(request, 'keyword.html', context)

def keyword_detail(request, pk):
    keyword = Keyword.objects.get(pk=pk)
    keyword.delete()
    return redirect('trends:keyword')

def crawling(request):
    keywords = Keyword.objects.all()
    result = []
    for keyword in keywords:      
        url = f"https://www.google.com/search?q={keyword.name}"
        # 크롬 브라우저가 열린다. 이 때, 동적인 내용들이 모두 채워짐
        driver = webdriver.Chrome(ChromeDriverManager().install())
        driver.get(url)

        # 열린 페이지 소스를 받아옴
        html = driver.page_source 
        soup = BeautifulSoup(html, "html.parser")

        # div 태그 중 id 가 result-stats 인 요소 검색
        result_stats = soup.select_one("div#result-stats")
        string_data = result_stats.text.split()[-2][:-1]
        result = int(string_data.replace(',', ''))

        if Trend.objects.filter(name=keyword.name, search_period="all").exists():
            trend = Trend.objects.get(name=keyword.name, search_period="all")
            trend.result = result
            trend.save()
        else:
          Trend.objects.create(name=keyword.name, result=result, search_period="all")
    
    trends = Trend.objects.filter(search_period="all")
    context = {
        'trends': trends
    }
    return render(request, 'crawling.html', context)


import matplotlib.pyplot as plt
plt.switch_backend('Agg')

import base64
from io import BytesIO

def crawling_histogram(request):
    trends = Trend.objects.filter(search_period="all")
    x = []
    y = []

    for trend in trends:
        x.append(trend.name)
        y.append(trend.result)

    # 그래프 초기화
    plt.clf()

    # 선 그래프 그리기
    # 큰 그림 생성
    plt.figure(figsize=(10, 6))  # 원하는 크기로 수정 (가로 10, 세로 6)
    plt.bar(x, y, label='Trends')

    # 축과 범례 설정
    plt.xticks(rotation=45)  # x 축 레이블 45도 회전
    plt.xlabel('Keyword')
    plt.ylabel('Result')
    plt.title('Technology Trend Analysis')
    plt.legend()
    plt.grid(True)

    # django view 에서 이미지 형식의 데이터를 직접 전송할 수 없음
    # 버퍼로 저장 -> template 으로 전송해야함
    # BytesIO(): 그래프 이미지를 임시로 저장할 버퍼
    buffer = BytesIO()
    # 그래프를 버퍼에 저장. 이미지 형식은 png 로 설정
    plt.savefig(buffer, format='png')
    # 버퍼의 내용을 base64 로 인코딩
    image_base64 = base64.b64encode(buffer.getvalue()).decode('utf-8').replace('\n', '')
    # data:image/png;base64:
    buffer.close()

    context = {
        'chart_image': f'data:image/png;base64,{image_base64}',
    }
    return render(request, 'crawling_histogram.html', context)

def crawling_advanced(request):
    keywords = Keyword.objects.all()
    result = []
    for keyword in keywords:      
        url = f"https://www.google.com/search?q={keyword.name}&tbs=qdr:y"
        # 크롬 브라우저가 열린다. 이 때, 동적인 내용들이 모두 채워짐
        driver = webdriver.Chrome(ChromeDriverManager().install())
        driver.get(url)

        # 열린 페이지 소스를 받아옴
        html = driver.page_source 
        soup = BeautifulSoup(html, "html.parser")

        # div 태그 중 id 가 result-stats 인 요소 검색
        result_stats = soup.select_one("div#result-stats")
        string_data = result_stats.text.split()[-2][:-1]
        result = int(string_data.replace(',', ''))
        
        if Trend.objects.filter(name=keyword.name, search_period="year").exists():
            trend = Trend.objects.get(name=keyword.name, search_period="year")
            trend.result = result
            trend.save()
        else:
          Trend.objects.create(name=keyword.name, result=result, search_period="year")

    # 지난 1년을 기준으로 검색한 결과 필터링
    trends = Trend.objects.filter(search_period="year")
    x = []
    y = []

    for trend in trends:
        x.append(trend.name)
        y.append(trend.result)

    # 그래프 초기화
    plt.clf()

    # 선 그래프 그리기
    # 큰 그림 생성
    plt.figure(figsize=(10, 6))  # 원하는 크기로 수정 (가로 10, 세로 6)
    plt.bar(x, y, label='Trends')

    # 축과 범례 설정
    plt.xticks(rotation=45)  # x 축 레이블 45도 회전
    plt.xlabel('Keyword')
    plt.ylabel('Result')
    plt.title('Technology Trend Analysis')
    plt.legend()
    plt.grid(True)

    # django view 에서 이미지 형식의 데이터를 직접 전송할 수 없음
    # 버퍼로 저장 -> template 으로 전송해야함
    # BytesIO(): 그래프 이미지를 임시로 저장할 버퍼
    buffer = BytesIO()
    # 그래프를 버퍼에 저장. 이미지 형식은 png 로 설정
    plt.savefig(buffer, format='png')
    # 버퍼의 내용을 base64 로 인코딩
    image_base64 = base64.b64encode(buffer.getvalue()).decode('utf-8').replace('\n', '')
    # data:image/png;base64:
    buffer.close()

    context = {
        'chart_image': f'data:image/png;base64,{image_base64}',
    }
    
    return render(request, 'crawling_advanced.html', context)

05_PJT/mypjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>트렌드 분석 애플리케이션</h1>
  <a href="{% url 'trends:keyword' %}">키워드 추가</a> |
  <a href="{% url 'trends:crawling' %}">크롤링</a> |
  <a href="{% url 'trends:crawling_histogram' %}">히스토그램</a> |
  <a href="{% url 'trends:crawling_advanced' %}">지난 1년 크롤링</a> |
  {% block content %}
  {% endblock content %}

</body>
</html>

05_PJT/mypjt/trends/templates/crawling.html
{% extends 'base.html' %}

{% block content %}
<h2>크롤링 기초 - 전체 기간 검색 결과</h2>

{% for trend in trends %}
<p>검색결과: {{ trend.name }} - {{ trend.result }}개 / 검색일자: {{ trend.created_at|date:"Y-m-d" }}</p>
<hr>

{% empty %}
<p>검색할 키워드가 없습니다</p>

{% endfor %}

{% endblock content %}

05_PJT/mypjt/trends/templates/crawling_advanced.html
{% extends 'base.html' %}

{% block content %}
<h2>지난 1년 간의 트렌드</h2>

<img src="{{ chart_image }}" alt="">

{% endblock content %}

05_PJT/mypjt/trends/templates/crawling_histogram.html
{% extends 'base.html' %}

{% block content %}
<h2>전체 기간 검색 결과 히스토그램</h2>

<img src="{{ chart_image }}" alt="">

{% endblock content %}

05_PJT/mypjt/trends/templates/keyword.html
{% extends 'base.html' %}

{% block content %}
<h2>키워드 추가</h2>

<form action="{% url 'trends:keyword' %}" method="POST">
  {% csrf_token %}
  <label for="keyword">키워드: </label>
  <input type="text" name="keyword">

  <input type="submit" value="생성하기">
</form>

<br>
<hr>

<h3>분석을 원하는 키워드 목록</h3>
{% for keyword in keywords %}

  <p>{{ keyword.id }}번째 키워드 - {{ keyword.name }}</p>
  <form action="{% url 'trends:keyword_detail' keyword.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제하기">
  </form>

  <hr>

{% empty %}
  <p>입력한 키워드가 없습니다.</p>
{% endfor %}

{% endblock content %}